service: ecocart
frameworkVersion: '3'

# useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  timeout: 30 #Second
  memorySize: 128 #MB
  
functions:
  ecocart:
    handler: build/handler.ecocart
    events:
       -   httpApi: '*'
    environment: 
      NW_AWS_REGION: us-east-1
      NW_AWS_DYNAMODB_ENDPOINT: http://dynamodb.us-east-1.amazonaws.com
      NW_AWS_ACCESS_KEY_ID: AKIAUS7X35MCHNSOXROH
      NW_AWS_SECRET_ACCESS_KEY: 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
      PORT: 5000
      NODE_ENV: developement
      DB_TABLE: EcoCart
      JWT_SECRET: ecocart
      JWT_EXPIRES_IN: 2d
      JWT_COOKIE_EXPIRES: 2

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
            
plugins:
  - serverless-offline
