name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          #### AWS KEYs ###### 
          AWS_ACCESS_KEY_ID: AKIAUS7X35MCHNSOXROH
          AWS_SECRET_ACCESS_KEY: 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